name: Deploy Astro Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker run -d --name ${{ github.event.repository.name }} --network web \
              -l "traefik.enable=true" \
              -l "traefik.http.routers.${{ github.event.repository.name }}.rule=Host(\`${{ vars.DOMAIN }}\`) || Host(\`www.${{ vars.DOMAIN }}\`)" \
              -l "traefik.http.routers.${{ github.event.repository.name }}.entrypoints=websecure" \
              -l "traefik.http.routers.${{ github.event.repository.name }}.tls.certresolver=myresolver" \
              -l "traefik.http.services.${{ github.event.repository.name }}.loadbalancer.server.port=80" \
              ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
